### ISSUE TITLE
Description / installation swapped?

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE-RefData#10]
These appear to be switched.  The stuff added as Description ends up in the lower half of the display with the title installation.  The installation data appears at the top without a header.

I think the order of the info is fine, just the title's displayed appear to be off.

I can barely add templated data, no way I could help fix this.

**Comment by SirGoodenough** [comment]
I noticed it because I referred to the installation section inside the description, but the description was titled installation, so.. I dug into it.

**Comment by SirGoodenough** [comment]
![Screenshot from 2020-06-26 21-39-03](https://user-images.githubusercontent.com/47349533/85913339-8edfe900-b7f9-11ea-96bb-9bcf2d804656.png)
Example of what it was doing.

**Comment by Blade2021** [comment]
Not sure what happened but the error is not able to be reproduced so we'll call it a fluke for now.
