### ISSUE TITLE
[FR]  Looking for a way to test references before they are merged into main

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE-RefData#34]
I have been updating a lot of references lately, and have been trying to add some emoji and formatting changes here and there.
  The problem is I make a change of any kind, and I don't know how it looks before it is loaded, and then have to iterate again with fixes to make it look nice.  In the mean time the odd formatting is left in production.
  I'm thinking a command in HIVE or in HIVE-ALPHA that I could send a json formatted reference entry to (copied right from reference or extended reference).  It would parse the json the same way HIVE will, returning the reference as it would look.  
  This would allow me to see the changes before I PR them for merge.
  I know you can tweak things because you have the whole environment and can tweak ALPHA to see stuff.  Others do not want and should not have that ability, but if we are to have the ability to do references, we also need a way to test them before submitting and wasting your time.

**Comment by Blade2021** [comment]
I'll move this to the HIVE repo for implementation.

**Comment by Blade2021** [comment]
New Request: https://github.com/Blade2021/HIVE/issues/75
