### ISSUE TITLE
[BR] {prefix} not working.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE-RefData#40]
The command that is supposed to replace ```{prefix}``` with `~` or whatever it happens to be is not functioning.  
This may not be new, not sure, so just reporting it for the to do list.

**Comment by SirGoodenough** [comment]
![Screenshot at 2021-07-01 23-03-49](https://user-images.githubusercontent.com/47349533/124219315-bb3fdc80-dac1-11eb-800a-e2255a32a15e.png)

**Comment by Blade2021** [comment]
Fixed.
